### PR TITLE
add weighting functionality

### PR DESCRIPTION
**Pull request by alyssafrazee**
r? @jocelynsarah 

@roban and I added support for weighted data! If you upload a scores file with a "weight" column, weights will be used as multipliers in the histogram calculation.

### CODE REVIEW

**Comment by jocelynsarah** [comment]
Does `check_alt_format` in this file also need to be updated?

**Comment by roban** [comment]
Oh, `check_alt_format` is interesting. This change doesn't break it because it's already binned, so you wouldn't provide weights if you are providing the alternate input format. But we could refactor it to _use_ a weight column (instead of just repeating rows) and be much faster and use less space.

**Comment by roban** [comment]
We refactored to use weights instead of repeating rows to transform the alt data format into a standard data frame.

**Comment by alyssafrazee** [comment]
:tulip: :tulip: hooray! :tulip: :tulip:

**Comment by roban** [comment]
I think we can consider this mutually reviewed, now. I'll leave it to you to merge, @alyssafrazee.

**Comment by jocelynsarah** [comment]
:star2:

**Pull request merged**
